services:
  db:
    image: mysql:8.0
    container_name: go_crud_mysql
    environment:
      MYSQL_DATABASE: go_crud
      MYSQL_USER: app
      MYSQL_PASSWORD: app
      MYSQL_ROOT_PASSWORD: root
      TZ: Asia/Tokyo
    ports:
      - "3307:3306"
    command: ["--default-authentication-plugin=mysql_native_password"]
    volumes:
      - dbdata:/var/lib/mysql

volumes:
  dbdata:
